drop table T_USER if exists
drop table T_ACCOUNT if exists

-- Tables
create table T_ACCOUNT (id bigint generated by default as identity (start with 1),identifier varchar(255) not null,uuid varchar(255), name varchar(255),primary key (id))
create table T_USER (id bigint generated by default as identity (start with 1),email varchar(255) not null,firstname varchar(255),lastname varchar(255),openid varchar(255),account_id bigint not null,primary key (id),foreign key (account_id) references T_ACCOUNT(id))


-- Data
insert into T_ACCOUNT (identifier, uuid, name) values ('nguyen_tan_nguyen','d58d7686-76cc-428e-b844-71efbb8e7727', 'Think Smart Inc')
insert into T_USER (email,firstname,lastname,account_id) values ('ntnguyen2603@gmail.com','Tan Nguyen', 'Nguyen',1)



